import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/Toaster";
import { cn } from "@/lib/utils";
import NavBar from "@/components/NavBar";
import SideNav from "@/components/SideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: " netly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn("bg-white text-slate-900 antialiased", inter.className)}
    >
      <body className="min-h-screen bg-custom-color antialiased fixed w-full">
        {/*typescript doesn't really know react server components (has problem with the async behavior of navbar so below comment is needed) */}
        {/* @ts-expect-error Server Component */}
        <NavBar />
        <SideNav />
        <div className="overflow-y-auto max-h-[calc(100vh)] top-0 mt-10  mx-auto h-full  right-0 left-0  rounded-tl-lg bg-white ml-18 fixed">
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
